version: '2'
services:
    jekyll:
        build: .
        image: registry.camderwin.us:5000/site:latest
        command: bundle exec jekyll serve --watch
        working_dir: /src
        volumes:
            - .:/src
        ports:
            - 3000:80
